# Generated by Django 4.2.1 on 2023-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('telephone', models.TextField(blank=True, max_length=255, null=True)),
                ('email', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
