# Generated by Django 4.2.1 on 2023-06-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_store', '0006_order_venda_orderitem_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venda',
            new_name='Sale',
        ),
    ]
