# Generated by Django 4.2.1 on 2023-06-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_store', '0007_rename_venda_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
